spring.application.name=emp-crud

server.port=${PORT:8080}


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d6qit6ma2pns73a1shmg-a.oregon-postgres.render.com:5432/empdb_glap
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sandeep
spring.datasource.password=NoPIfZPthJPAlWE63ymOeWgIw2KWEuQU


# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true