spring.application.name=emp-crud

server.port=${PORT:8080}

# H2 Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d6p6bkh5pdvs739so8tg-a.render.com/empdb_cgtp
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=sandeep
spring.datasource.password=UdRV1I9UkzdD0mycNbdORUYkJaL2Zdyd

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

